### ISSUE TITLE
Chunk by census block groups

### ISSUE THREAD

**Issue by lxbarth** [osmlab/dcbuildings#12]
Use census block groups for more granular chunks to upload:
- http://dcatlas.dcgis.dc.gov/catalog/results.asp?pretype=All&alpha=C

/cc @mikelmaron 
## Tracts

_This is what we're using now to chunk up data._

![screen shot 2013-08-04 at 4 35 09 pm](https://f.cloud.github.com/assets/98233/907539/86dfae28-fd45-11e2-8550-ca15dfb47e6f.png)
## Block groups

![screen shot 2013-08-04 at 4 35 17 pm](https://f.cloud.github.com/assets/98233/907541/8b682f88-fd45-11e2-878d-912e20f7655e.png)

Update: edited to use block groups.

**Comment by andinocl** [comment]
+1 for block groups for initial import (allows more hands, closer bathroom breaks).

**Comment by lxbarth** [comment]
@andinocl agreed.
