### ISSUE TITLE
Expand abbreviations

### ISSUE THREAD

**Issue by lxbarth** [osmlab/dcbuildings#15]
Expand all `NW` and `Rd` etc. Addresses should match street names.

**Comment by jremillard** [comment]
I just looked at the code, and I don't see the full expansion list from Serge's tiger bot integrated. Just doing NW,SW, etc, is not enough??

**Comment by lxbarth** [comment]
@jremillard - rest is already expanded. DC doesn't abbreviate like US Census does.
