### ISSUE TITLE
Upload user account

### ISSUE THREAD

**Issue by lxbarth** [osmlab/dcbuildings#18]
WIth multiple individuals reviewing and uploading data, should we:
1. Have one upload account per individual?
2. One upload account for the import effort that we share between individuals?

**Comment by jremillard** [comment]
Don't wan't #2. Option 3 would be to have everybody QA all of the OSM files and have one person actually upload them at the end. #1 is fine too.

**Comment by lxbarth** [comment]
Baesed on standing [Import Guidelines](http://wiki.openstreetmap.org/wiki/Import/Guidelines#Use_a_dedicated_user_account) we will use one user account per individual for this import.

Pattern: `<regularusername>_dcbuildingsaddresses`
