### ISSUE TITLE
How are buildings that are intersected by block boundaries handled ? 

### ISSUE THREAD

**Issue by oldtopos** [osmlab/dcbuildings#25]
I noticed in a dataset I've been experimenting with that census block group boundaries can intersect building geometry, so that a simple intersection check will generate duplicate buildings at those boundaries, as those cases intersect multiple block groups.

I dealt with this by assigning buildings to a block group via contains, which does not report intersecting geometries.  I then used an intersection checks; which assigns all buildings not picked up by contains to a single block group.

**Comment by lxbarth** [comment]
@oldtopos - a building that's on a block boundary will show up in both blocks as we're using shapely's [intersects](http://toblerity.org/shapely/manual.html#object.intersects).
