### ISSUE TITLE
Add task on tasks.osm.us

### ISSUE THREAD

**Issue by lxbarth** [osmlab/dcbuildings#27]
Now that #19 is done, deploy a task on tasks.openstreetmap.us.

Needs #12 first.

**Don't deploy before final go on import.**

**Comment by mikelmaron** [comment]
@pgiraud @MateoV @iandees shall we make pull request and accept on https://github.com/MateoV/osm-tasking-manager/commit/41db7ef75c462005326933bb1328e1d2e4fc75c4, and then deploy from master?

**Comment by emacsen** [comment]
Does this task deployment mean that users will start doing the tasks?

**Comment by emacsen** [comment]
Got a message that it's not. Will remove the stick from my rear end.

**Comment by MateoV** [comment]
@emacsen Sorry, pulled the trigger before I realized this was a different issue thread.

To answer your question, the deployment Mikel is referring to is just for the task manager code. Once the dcbuildings task is created on tasks.osm.us it will be live. It can also be made private until ready to go live if timing is a concern.

**Comment by emacsen** [comment]
Yes, timing is a concern.

I think it's great that the github exists with the software, the history, the discussion, but this import differs from the previous one, and should be treated like a new import (after 2 years and a completely new software stack, as well as new import process, I'd argue it's an entirely new import). It should then follow the OSM Import Guidelines, ie a wiki page, a message to the imports list and time to allow others to examine the import. It would also be nice if the US Import Committee were part of the discussion as well (that's not in the guideline, but it would be nice).

I think it's great you all have done all this work, and I'm sure you're anxious to see the fruits of your labor, but to avoid the problems we've had in the past, we want to get some larger community involvement.

**Comment by lxbarth** [comment]
> Does this task deployment mean that users will start doing the tasks?

No. Updated ticket accordingly.

**Comment by lxbarth** [comment]
Also calling this "add" not "deploy" now as this is causing confusion. This ticket is about adding the dcbuilding task to tasks.osm.us

**Comment by lxbarth** [comment]
Task is added needs documentation now: http://tasks.openstreetmap.us/job/6
