### ISSUE TITLE
Document task on tasks.openstreetmap.us

### ISSUE THREAD

**Issue by lxbarth** [osmlab/dcbuildings#30]
Document

http://tasks.openstreetmap.us/job/6

Like

http://tasks.openstreetmap.us/job/2

**Comment by tmcw** [comment]
Um, is that manager down/oauth is messed up? https://gist.github.com/tmcw/7090160

**Comment by lxbarth** [comment]
@tmcw - try again. I think that was @iandees doing heart surgery on the DB. I put up the task again.

**Comment by tmcw** [comment]
yep, fixed.

**Comment by geobrando** [comment]
Pool of contributors ended up being very small after [OCTO](http://octo.dc.gov/) took the reins.  Information usually contained in **Description** and **Workflow** was communicated offline.  No need for this now as we're nearing completion, but we should definitely comply with this if we use the tasking manager for additional import/clean up work.
