### ISSUE TITLE
Delete job/5

### ISSUE THREAD

**Issue by lxbarth** [osmlab/dcbuildings#31]
@iandees - How does one delete a task? Can you do this?

http://tasks.openstreetmap.us/job/5 is obsolete.

**Comment by iandees** [comment]
One does not delete a task. It might be possible in the database, but I haven't looked. I think the best you can do is archive or mark it private.

**Comment by lxbarth** [comment]
How can i archive or set private? Seems i don't have the powers.

http://twitter.com/lxbarth

**Comment by geobrando** [comment]
I was able to archive it
