### ISSUE TITLE
OSM changes to DC gov using changewithin?

### ISSUE THREAD

**Issue by geobrando** [osmlab/dcbuildings#33]
@lxbarth Was the possibility of regular updates to [DC OCTO](http://octo.dc.gov/) or other interested parties using [changewithin](https://github.com/osmlab/changewithin) ever discussed, similar to what you're doing in [NYC](https://www.mapbox.com/blog/nyc-and-openstreetmap-cooperating-through-open-data/)?  Is there a license impediment?

**Comment by lxbarth** [comment]
@geobrando - nothing's in the way of setting up a changewithin instance for DC, too. It's a good indication of what building and address data has changed on OSM - information that is potentially very useful for DC. Only thing impeded by the license is that it's not possible to copy data directly from OSM into the OCTO dataset.

**Comment by geobrando** [comment]
@davidyjackson Can you take a look at this and see if this is something that OCTO would be interested in?

@lxbarth If this is desired, I'm sure you and Mapbox could easily handle setting this up, but we could also maintain this through MappingDC.

**Comment by lxbarth** [comment]
@geobrando - as this is very easy to set up on a server ideally it's run by whoever is the main subscriber to the email notifications.

**Comment by geobrando** [comment]
@lxbarth Sure, but I thought the point was that you take the burden off the local gov or whatever so all they need to is provide an email address and a geography.  I assumed NYC received change emails generated from an external server.  Either way.

**Comment by lxbarth** [comment]
> I assumed NYC received change emails generated from an external server. Either way.

They run their own.
