### ISSUE TITLE
Addresses are missing city, state and country tags

### ISSUE THREAD

**Issue by talllguy** [osmlab/dcbuildings#34]
Pardon me if this was decidedly not included in the import. It seems that many of the data are missing the `addr:city` key, as well as `addr:state=DC` _debatable_ and `addr:country=US`. To observe these issues, either use [Unvollständige Adressen](http://osm.lyrk.de/address/#17/38.92798/-77.00833) or run this query on [Overpass Turbo](http://overpass-turbo.eu/s/4JU):

```
<osm-script output="json" timeout="25">
  <!-- gather results -->
  <union>
    <query type="node">
      <has-kv k="addr:housenumber"/>
      <has-kv k="addr:city" modv="not" regv="."/>
      <bbox-query {{bbox}}/>
    </query>
    <query type="way">
      <has-kv k="addr:housenumber"/>
      <has-kv k="addr:city" modv="not" regv="."/>
      <bbox-query {{bbox}}/>
    </query>
    <query type="relation">
      <has-kv k="addr:housenumber"/>
      <has-kv k="addr:city" modv="not" regv="."/>
      <bbox-query {{bbox}}/>
    </query>
  </union>
  <!-- print results -->
  <print mode="body"/>
  <recurse type="down"/>
  <print mode="skeleton" order="quadtile"/>
</osm-script>
```

**Comment by geobrando** [comment]
Hey there.  I wasn't involved with crafting the import plan, but there was clearly a choice made not to import state and city tags or append with US.  See [convert.py](https://github.com/osmlab/dcbuildings/blob/master/convert.py)

My understanding is that these are often considered optional.  Check out the `addr:street` section on [this](http://wiki.openstreetmap.org/wiki/Key:addr) wiki page.

**Comment by lxbarth** [comment]
I think this is fine. The `addr:city`, `addr:country` and `addr:state` keys are redundant. In a geocoder you'd typically use polygon data to determine the place portion of an address.

Closing?
