### ISSUE TITLE
Add addresses

### ISSUE THREAD

**Issue by lxbarth** [osmlab/dcbuildings#4]
- Add address data to buildings where only one address per building
- Export addresses as separate nodes where there are 2 or more addresses per building

**Comment by andinocl** [comment]
I'm in the middle of a longer email, but I think http://stackoverflow.com/questions/13823122/check-if-multipolygon-contains-point-in-postgis is part of the solution. Essentially, we'd need to write a function that queries the COUNT of the points contained by the building multipolygon.  If less than 2, it combines, if 2 or more, it does not combine and instead exports the address nodes.

**Comment by lxbarth** [comment]
@andinocl - merging in address data is already taken care of, it just needs to be exported along the lines of what you suggest. Merge if there is a 1 to 1 relationship between building and addresses, export address separately otherwise. I don't think we need PostGis for this. See TODOs in code:
- https://github.com/osmlab/dcbuildings/blob/3cf9fe6b7b9cf3689ce60c5e916a127fece305c5/convert.py#L45
- https://github.com/osmlab/dcbuildings/blob/3cf9fe6b7b9cf3689ce60c5e916a127fece305c5/convert.py#L62
