### ISSUE TITLE
Double check spatial match between addresses and buildings

### ISSUE THREAD

**Issue by lxbarth** [osmlab/dcbuildings#6]
We're currently just using rtree and a bounding box test to check whether an address location is within a building.

This is likely too coarse, leading to many false positives.
- Double check whether we have indeed many false positives
- Add a point in polygon test after the bounding box test before associating an address with a building

**Comment by ian29** [comment]
we actually may want to consider pointinpolygon in favor of centroids/bounding boxes. think of irregular buildings where the bounds would return points not inside the building polygon: 

http://www.openstreetmap.org/browse/way/67087300
