### ISSUE TITLE
Multipolygon handling

### ISSUE THREAD

**Issue by andinocl** [osmlab/dcbuildings#7]
For complex buildings like http://www.openstreetmap.org/browse/relation/1029369 the OSM tag data is saved in the relation.  Currently, convert.py does not handle multipolygons; we'll need to devise a way to do that (probably via differences) and programatically create a relation to append the tag data to. This will also be a problem in reverse (managing multipolygons in the planet.osm file to see whether the building already exists in the OSM data).

**Comment by lxbarth** [comment]
We're handling this now: https://github.com/osmlab/dcbuildings/commit/7b89cf17842738bbbc5d6db348f9d103a16a6c06
