### ISSUE TITLE
Consider including separated street name information

### ISSUE THREAD

**Issue by iandees** [osmlab/dcbuildings#8]
Since the shapefile for the addresses includes information about the parts of the street name, consider including that in the OSM data too.

I did this [in Chicago](http://www.openstreetmap.org/browse/way/209839548). Not sure if it's particularly useful yet, but I figure why lose some information about the street name by only including the merged name.

**Comment by lxbarth** [comment]
Do you really think that's a good idea?

Here's my thinking: you'd have to capture address partials in a location proprietary way, limiting its usefulness. It's not that OSM has a global standard for address partials, or does it?

**Comment by lxbarth** [comment]
Won't do this.
